-- Exploring all objects of the database
select * from INFORMATION_SCHEMA.TABLES

-- Explore all columns in database or specific table
select * from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME = 'dim_customers'

----------------------------------------------
-- Exploring Dimensions 
----------------------------------------------
----------------------------------------------

-- Countries our customers come from
----------------------------------------------
select DISTINCT counrty 
from gold.dim_customers


-- out caterories
select DISTINCT category,
				subcategory,
				product_name
from gold.dim_product
order by    category ,
			subcategory ,
			product_name

----------------------------------------------
-- Exploring dates
----------------------------------------------
select
min(order_date) AS first_order_date,
max(order_date) AS last_order_date,
DATEDIFF(year,min(order_date),max(order_date))AS years_range
from gold.fact_sales

-- Exploring customer ages range
select
min(birthdate) AS oldest_customer ,
DATEDIFF(year,min(birthdate),GETDATE()) AS oldest_customer_age,
max(birthdate) AS youngest_customer,
DATEDIFF(year,max(birthdate),getdate()) AS youngest_customer_age
from
gold.dim_customers


----------------------------------------------
-- Exploring maesures 
----------------------------------------------
----------------------------------------------

-- Total sales
select
sum(sales_amount)
from gold.fact_sales

-- How many items were sold
select
sum(quantity)
from gold.fact_sales

-- Average selling price
select
avg(price)
from gold.fact_sales

-- Total numbers of orders
select
count(order_number)
from gold.fact_sales
--------------------------------------
select
count(DISTINCT order_number)
from gold.fact_sales

-- Total numbers of products
select 
count(product_name)
from
gold.dim_product 

-- Total numbers of customers
select
count(DISTINCT customer_key)
from gold.dim_customers

--Total numbers of customers that had placed an order
select
count(DISTINCT customer_key)
from gold.fact_sales
-----------------------------------------------------------------------------------------
-- Generating Report Shows All Key Matrics Of The Business
-----------------------------------------------------------------------------------------
select 'Total Sales' AS Measuer_name ,
sum(sales_amount) AS Measure_value 
from gold.fact_sales

UNION ALL

select 'Total Quantity' ,
sum(quantity)
from gold.fact_sales

UNION ALL

select 'Average Selling Price' ,
AVG(price)
from gold.fact_sales

UNION ALL

select 'Total Orders' ,
count(DISTINCT order_number)
from gold.fact_sales

UNION ALL

select 'Total Number of Products' ,
count(DISTINCT product_key)
from gold.dim_product 

UNION ALL

select 'Total Number of Customer' , count(DISTINCT customer_key)from gold.dim_customers
-----------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------
--Magnitude Analysis
--------------------------------------

-- Find total customers by countries
select 
counrty AS Counrty,
count(customer_key) AS Total_Customers
from
gold.dim_customers
GROUP BY 
Counrty
ORDER BY Total_Customers DESC

-- Find total customers by gender
select
gender AS Gender,
count(customer_key) AS Total_Customers
from
gold.dim_customers
GROUP BY 
Gender
ORDER BY 
Total_Customers
DESC

-- Find total products by category
select 
category AS Category,
count(product_key) AS Number_of_Products
FROM
gold.dim_product
GROUP BY 
Category
ORDER BY 
Number_of_Products
DESC

-- What is the average costs in each category?
select 
category AS Category,
Avg(cost) AS Average_Cost_Price
from
gold.dim_product
GROUP BY 
Category
ORDER BY 
Average_Cost_Price
DESC

-- What is the total revenue generated for each category?
select 
productt.category AS Category,
sum(sales.sales_amount) AS Total_Revenue
from
gold.fact_sales sales
left join
gold.dim_product productt
on
sales.product_key = productt.product_key
GROUP BY 
Category
ORDER BY
Total_Revenue
DESC

-- Find total revenue is generated by each customer
select 
cus.customer_key  ,
cus.first_name  ,
cus.last_name,
sum(sales.sales_amount) AS Total_Revenue
from
gold.fact_sales sales
left join
gold.dim_customers cus
on
sales.customer_key = cus.customer_key
GROUP BY 
cus.customer_key,
cus.first_name,
cus.last_name
ORDER BY
Total_Revenue
DESC
